const express = require('express')
const fs = require('fs').promises
const path = require('path')
const app = express()
app.use(express.json())
app.use(express.static(path.join(__dirname)))
const planningFile = path.join(__dirname, 'data', 'planning.json')
const usersFile = path.join(__dirname, 'data', 'users.json')
app.get('/api/planning', async (_, res) => { const d = await fs.readFile(planningFile, 'utf8'); res.json(JSON.parse(d)) })
app.put('/api/planning', async (req, res) => { await fs.writeFile(planningFile, JSON.stringify(req.body, null, 2), 'utf8'); res.sendStatus(204) })
app.get('/api/users', async (_, res) => { const d = await fs.readFile(usersFile, 'utf8'); res.json(JSON.parse(d)) })
app.put('/api/users', async (req, res) => { await fs.writeFile(usersFile, JSON.stringify(req.body, null, 2), 'utf8'); res.sendStatus(204) })
app.listen(3000)
